# Default values for bbrf-server.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

couchdb:
  username: admin
  password: COUCHDB_PASSWORD_CHANGE_ME_MUST!
bbrf:
  password: BBRF_PASSWORD_CHANGE_ME_MUST!

image:
  repository: honoki/bbrf-server
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

persistence:
  enabled: false
  ## database data Persistent Volume Storage Class
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  # storageClass: "-"
  name: bbrf-pvc-claim0
  accessMode: ReadWriteOnce
  size: 20Gi
  annotations: {}
  storageClass: local-path


imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
# fsGroup: 2000

securityContext: {}
# capabilities:
#   drop:
#   - ALL
# readOnlyRootFilesystem: true
# runAsNonRoot: true
# runAsUser: 1000

service:
  name: bbrf-db-svc
  port: 5984
  type: ClusterIP

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_input_headers "X-Real-IP: $remote_addr";
      more_set_input_headers "X-Forwarded-For: $proxy_add_x_forwarded_for"
      more_set_input_headers "X-NginX-Proxy: true"
      more_set_input_headers "Host: $http_host"
    nginx.ingress.kubernetes.io/proxy-ssl-session-reuse: "off"
    nginx.ingress.kubernetes.io/proxy-cache-bypass: "$http_upgrade"
    nginx.ingress.kubernetes.io/proxy-redirect: "off"
    nginx.ingress.kubernetes.io/proxy-body-size: "4g"
    nginx.ingress.kubernetes.io/proxy-compression: "on"
    nginx.ingress.kubernetes.io/proxy-compression-types: "application/json"
    kubernetes.io/ingress.class: nginx
  # kubernetes.io/tls-acme: "true"
  hostname: chart-example.local
  path: /(.*)
  pathType: Prefix
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
# We usually recommend not to specify default resources and to leave this as a conscious
# choice for the user. This also increases chances charts run on environments with little
# resources, such as Minikube. If you do want to specify resources, uncomment the following
# lines, adjust them as necessary, and remove the curly braces after 'resources:'.
# limits:
#   cpu: 100m
#   memory: 128Mi
# requests:
#   cpu: 100m
#   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
